### ISSUE TITLE
Public calendar integration

### ISSUE THREAD

**Issue by nhyty** [newtheatre/website#1]
A way/page for people to have a public NNT calendar which they can sync to their own

**Comment by wjdp** [comment]
*See #8 (user groups)* Who is the calender for, punters or members?

**Comment by wjdp** [comment]
Re. today this is a thing: http://members.newtheatre.org.uk/calendar, all committee can add items to.

**Comment by wjdp** [comment]
This is a thing, just needs to be used. Will close.
