### ISSUE TITLE
Room Bookings

### ISSUE THREAD

**Issue by harry-bridge** [newtheatre/website#12]
Make it look prettier, looks rather balls at the moment

**Comment by nhyty** [comment]
oh yeah, i forgot about that page

**Comment by wjdp** [comment]
Go nuts, http://mrbs.sourceforge.net/, is probably going to be fairly horrible code to go through

**Comment by pickleshb** [comment]
may have a look tomorrow, where is it hosted atm?

**Comment by wjdp** [comment]
stairs
