### ISSUE TITLE
Don't break links

### ISSUE THREAD

**Issue by wjdp** [newtheatre/website#14]
![image](https://cloud.githubusercontent.com/assets/1690934/12500142/4f56380e-c0a8-11e5-85f5-e8c2b05bfe2f.png)

We're not allowed to break links between the current and the new site. All links should be kept the same or redirect to the new link.
- [ ] Build a list of links
- [ ] Don't break them

**Comment by wjdp** [comment]
Some tweaked in ec630711a0535ee2a0b6e0ae3ecffa94fab3bcbd but `redirect_from` specified.

**Comment by nhyty** [comment]
closed in #27
