### ISSUE TITLE
Logo assets

### ISSUE THREAD

**Issue by wjdp** [newtheatre/website#15]
The following need making

- [ ] SVG of NNT Logo, white on black
- [ ] SVG of NNT Logo, black on white
- [ ] Big PNGs of above

**Comment by pickleshb** [comment]
Seen as I have most of the NT logo already in AI I can get on this, do we know the typeface that was used?

**Comment by wjdp** [comment]
Sweet, cheers.

Font is Akkurat, can be obtained here: http://members.newtheatre.org.uk/publicity:logos_branding. There is an EPS file there which may be of some use.

**Comment by pickleshb** [comment]
It would be useful, if the links to them weren't broken. The fonts and colours are useful though

**Comment by wjdp** [comment]
Ah, links fixed now

**Comment by pickleshb** [comment]
Danke
