### ISSUE TITLE
Use of typefaces (Myriad Pro --> Akkurat)

### ISSUE THREAD

**Issue by wjdp** [newtheatre/website#16]
Theatre seem to be using Myriad Pro for things (bottom of posters). The logotype is Akkurat (SU has licence)

Myriad is a commercial font, Adobe TypeKit licence will be required to use on site ($50 USD/year) bit of a PITA.

I seem to remember SU has some licence for Akkurat, we should investigate this.

**Comment by wjdp** [comment]
Looks like any licence SU would have had was for print/graphic use, web licence for Akkurat is 270 CHF (~£195). I suggest looking for open alternatives.

**Comment by pickleshb** [comment]
@wjdp Roboto?

**Comment by wjdp** [comment]
We've got open sans as the body face, Roboto looks too similar. Looking for something for the header face, or approval of HP's Montserrat.
