### ISSUE TITLE
Show data files

### ISSUE THREAD

**Issue by wjdp** [newtheatre/website#19]
For show data we will use a collection of pages and mirror a subset of the fields used for history project pages (https://history.newtheatre.org.uk/docs/shows/).

What additional data would be nice to have for the "online programme"?
- Images
- Director/producer notes
- Cast notes
- Cast(/crew) headshots
- Sponsors

Advantage of using same data file as HP is easy migration from website to HP.

**Comment by nhyty** [comment]
this is not how we are doing the site and i feel that that is fine
