### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by wjdp** [newtheatre/website#21]
MailChimp list, the signup for it is here http://newtheatre.org.uk/about-us/mailing-list/ and it does automatically when you book tickets. 

It's not been sent to since June 2015 and has the larget number of _confirmed_ subscribers.

Decide what to do with this.

![image](https://cloud.githubusercontent.com/assets/1690934/14093114/6ce4587c-f543-11e5-910c-3bc76bd7fb77.png)

**Comment by pickleshb** [comment]
Should we move this over to SES as that can be set up as a mailing list thingy

**Comment by wjdp** [comment]
MailChimp was chosen originally for having a nice UI for marketing peeps to send pretty emails out. If SES has similar then that could be something worth doing, but I would leave on the backlog while we have many other things to do.

**Comment by pickleshb** [comment]
Just an idea, I will look into it a bit more, I'm sure I could set up an automated marketing email rather easily

**Comment by davidtaylorhq** [comment]
SES does not have a pretty interface in the slightest. As far as I know it is purely an email sending service (basically an SMTP server). It doesn't even provide list management. 
Mailchimp is probably a better choice, and I expect it has some kind of API if you really wanted to create automatic emails

**Comment by wjdp** [comment]
Ah, then yep, probably best to stick with MC. It does have an API, is how old tickets subscribed people. On that note @pickleshb, does new tickets do this?

**Comment by pickleshb** [comment]
It is just an endpoint, I would have to manage the mailing list in Django, if we're happy to pay for mailchimp then we can use that

**Comment by wjdp** [comment]
For our usage it's free.

**Comment by nhyty** [comment]
Add a new page similar to show resources with an iframe for the signup or just link to the signup form???
