### ISSUE TITLE
Committee headshots via Smugmug

### ISSUE THREAD

**Issue by wjdp** [newtheatre/website#22]
I've stuck the committee listing in a [data file](https://github.com/newtheatre/website/blob/master/_data/committee.yml).

Get headshots into an unlisted album on smuggy and get the image IDs into a `headshot` var in the data file.

**Comment by nhyty** [comment]
Added to SM

**Comment by wjdp** [comment]
Can you copypasta the IDs over? http://api.smugmug.com/api/v2/album/nnh95H!images

**Comment by wjdp** [comment]
(Work on staging branch, GH won't let you push to master)

**Comment by nhyty** [comment]
@wjdp Sure, i will at some point today

**Comment by BenWoodford76** [comment]
Sorted in New Website
