### ISSUE TITLE
Page for display screens

### ISSUE THREAD

**Issue by davidtaylorhq** [newtheatre/website#25]
Make a page, hidden from robots & with no navigation, which is designed for displaying on the screens in the foyer. Should have show information, and pretty pictures (maybe a smugmug slideshow of some description).

**Comment by nhyty** [comment]
@pickleshb wow, nice commit message :)

**Comment by wjdp** [comment]
http://blogs.wcode.org/2013/09/howto-boot-your-raspberry-pi-into-a-fullscreen-browser-kiosk/

**Comment by pickleshb** [comment]
This is rather useful

**Comment by davidtaylorhq** [comment]
It is indeed, think it's the same process I used for my mirror
![img_0278](https://cloud.githubusercontent.com/assets/6270921/14142008/c3d33814-f67a-11e5-874d-87c54dd80a84.JPG)

**Comment by pickleshb** [comment]
I need to make myself one of those

**Comment by wjdp** [comment]
ditto, been on the backlog for years

**Comment by pickleshb** [comment]
I have a screen, just need to get the right sized mirror
