### ISSUE TITLE
Ticket Pricing

### ISSUE THREAD

**Issue by nhyty** [newtheatre/website#28]
Display a link to a Bootstrap modal under 'Reserve tickets' displaying a table as per `pricing.yml`
Conditional relating to the season of the show 
modal:
	if in house
		display in house and all 
	if fringe 
		display fringe and all
	if stuff
		display stuff 
	else 
		display please email foh@ for ticket pricing information

**Comment by nhyty** [comment]
It may be easier to get this onto the ticket reservation modal through nt-tickets

**Comment by nhyty** [comment]
most likely through book landing.html

**Comment by samozzy** [comment]
Resolved via nt-tickets
