### ISSUE TITLE
Address

### ISSUE THREAD

**Issue by nhyty** [newtheatre/website#3]
Add a google map link for us in the footer so people know where we are, also add directions to nearest car parks and where the car parks are.

**Comment by pickleshb** [comment]
Google still has us a [old engineering]
(https://www.google.co.uk/maps/@52.9378852,-1.1965631,117m/data=!3m1!1e3) though, very confusing

**Comment by nhyty** [comment]
Yeah, working on that

**Comment by wjdp** [comment]
Building was engineering prior to archaeology and classics. The fake ceilings were attached to bits of crane in the roof.

**Comment by nhyty** [comment]
Cool

**Comment by wjdp** [comment]
We're also a *"Theater"* 
![image](https://cloud.githubusercontent.com/assets/1690934/12360948/edc40228-bbb2-11e5-966f-45063a303898.png)

**Comment by pickleshb** [comment]
Apparently ...

**Comment by nhyty** [comment]
I've tried fixing it but google are slow

**Comment by pickleshb** [comment]
I put in a request a while ago but nothing has seemed to have happened

**Comment by nhyty** [comment]
:agree

**Comment by wjdp** [comment]
Someone (the tech manager gmail) needs to take control of the business. You get a postcard with a code sent to the address for validation.

**Comment by nhyty** [comment]
if you know how to do that please do will, you still know the password

**Comment by wjdp** [comment]
Done, address on record isn't great but should arrive within a week

**Comment by nhyty** [comment]
Awesome, I'll check SU reception for it

**Comment by wjdp** [comment]
Any sight of postcard? @nhyty

**Comment by wjdp** [comment]
I'm presuming not, I've requested another
