### ISSUE TITLE
Link to gallery

### ISSUE THREAD

**Issue by nhyty** [newtheatre/website#4]
There should be a way to get to the gallery on the website, don't know where exactly though

**Comment by wjdp** [comment]
the gallery?

**Comment by nhyty** [comment]
photos.newtheatre.org.uk

**Comment by wjdp** [comment]
ah

**Comment by nhyty** [comment]
add this link to the footer @samozzy ???

**Comment by samozzy** [comment]
@nhyty How much do we publicise the gallery as a resource? Should we?

**Comment by nhyty** [comment]
@samozzy atm, not much at all, i think we should do so more
