### ISSUE TITLE
No booking info if pricing is not retrieved from the database 

### ISSUE THREAD

**Issue by samozzy** [newtheatre/website#48]
Returns a blank iframe 
@davidtaylorhq - is this something you can look into?

**Comment by davidtaylorhq** [comment]
Is there an example show for this bug? Or if not, can you describe in more detail what causes the issue?

**Comment by samozzy** [comment]
Set show season to external (or StuFF) (can be seen with test show currently on 1st June)
Reload what's on page 
Click reserve tickets 

Booking page does not load

**Comment by samozzy** [comment]
@samozzy

**Comment by davidtaylorhq** [comment]
Closed by https://github.com/newtheatre/nt-tickets/commit/b64d6cf41fb891e5085218cb6f1c7f4496f8e03c
