### ISSUE TITLE
New NSDF graphics

### ISSUE THREAD

**Issue by nhyty** [newtheatre/website#5]
Emma is going to creat one for Ritual from last year, will then replace on homepage and can it be added to the footer.

**Comment by wjdp** [comment]
I've a folder of many PSDs, will upload

**Comment by wjdp** [comment]
Also win all the awards this year :)

**Comment by nhyty** [comment]
Unsure as to whether we care that much about this anymore given NSDF doesn't select, and admits as much, the best shows they see. thoughts @samozzy

**Comment by samozzy** [comment]
@nhyty Would say it's still an achievement worth publicising; that said I don't know where the graphics would go

**Comment by nhyty** [comment]
@samozzy exactly, feel like facebook page is more appropriate perhaps?

**Comment by nhyty** [comment]
@nhyty nd long term we will have it on the HP

**Comment by nhyty** [comment]
do we want this on the website, i'm gonna say probs not
