### ISSUE TITLE
Pages to be edited

### ISSUE THREAD

**Issue by nhyty** [newtheatre/website#6]
Will add a list f pages being rewritten/updated by committee, hopefully done by start of the new season.

**Comment by wjdp** [comment]
I've pushed lots from the existing site into `_content/`, have a look through and assign. There's still a lot out of date and a certain level of cringe in some.

**Comment by wjdp** [comment]
@nhyty can you engage committee to try and get some work done on this?

**Comment by nhyty** [comment]
@wjdp Will poke people to do this myself.
